library(parallel)
library(doMC)
registerDoMC(cores=detectCores())
library(STREM)
source("~/git/STREM/setup/WTC-Boot.R")

study <- getStudy("A")
transects <- FinlandRandomForestWTCSurveyRoutes$new(study=study)
transects$randomizeSurveyRoutes(500)
#transects$loadSurveyRoutes()
habitatWeights <- CORINEHabitatWeights$new(study=study)
transects$getLengthsByHabitatType(habitatWeights, debug=TRUE)
transects$saveSurveyRoutes()

transects$getSurveyRoutesFileName()
