// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// internal_countIntersections
SEXP internal_countIntersections(Rcpp::NumericMatrix track, Rcpp::NumericMatrix surveyRoute);
RcppExport SEXP WTC_internal_countIntersections(SEXP trackSEXP, SEXP surveyRouteSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type track(trackSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type surveyRoute(surveyRouteSEXP );
        SEXP __result = internal_countIntersections(track, surveyRoute);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
